version: '3.8'

services:
  app:
    build:
      context: php
      dockerfile: Dockerfile
    container_name: tawreedaat
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=live
      - DB_USERNAME=live
      - DB_PASSWORD=Engineer@01258
    volumes:
      - ./application:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini # Custom PHP configuration
    depends_on:
      - db
    networks:
      - backend
    command: >
      sh -c "chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache && php-fpm"

  web:
    image: caddy:latest
    container_name: tawreedaat_caddy
    working_dir: /var/www/html
    volumes:
      - ./application:/var/www/html
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    networks:
      - backend

  db:
    image: mysql:8.0
    container_name: tawreedaat_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: live
      MYSQL_USER: live
      MYSQL_PASSWORD: Engineer@01258
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

volumes:
  db_data:

networks:
  backend:
    driver: bridge
