version: '3.8'
services:
  app:
    build:
      context: php
      dockerfile: Dockerfile
    container_name: tawreedaat
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=live
      - DB_USERNAME=live
      - DB_PASSWORD=Engineer@01258ction
    volumes:
      - ./application:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini # Custom PHP configuration
    depends_on:
      - db
  # web:
  #   image: nginx:alpine
  #   container_name: laravel_web
  #   working_dir: /var/www/html
  #   volumes:
  #     - .:/var/www/html
  #     - ./nginx.conf:/etc/nginx/nginx.conf # Custom Nginx configuration
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - app

  web:
    image: caddy:latest
    container_name: tawreedaat_caddy
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app


  db:
    image: mysql:8.0
    container_name: tawreedaat_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: live
      MYSQL_USER: live
      MYSQL_PASSWORD: Engineer@01258
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
